#server.port=8086
#spring.datasource.url=jdbc:mysql://localhost:3306/jwt_token
#spring.datasource.username=root
#spring.datasource.password=9430
#spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver
#spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQL5Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
#
#jwt.secret=secretKey
#
#spring.security.oauth2.client.registration.google.client-id=368029334897-2fbahd99p3p5m9amh7v4t4gtpudhtns0.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.client-secret=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



spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/hrms
    password: 'root'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      ddl-auto: update
server:
  port: '8080'
jwt:
  secret: secretKey
